import type { BoardDefinition } from '@/board/boardTypes';

export const mountCinderBoardDefinition: BoardDefinition = {
  id: 'mount-cinder',
  name: 'Mount Cinder',
  objectiveNodeId: 'heartstone-dais',
  escapeNodeId: 'smugglers-dock',
  nodes: [
    {
      id: 'smugglers-dock',
      label: "Smuggler's Dock",
      position: [0, 0.5, 19],
      neighbors: ['lower-west', 'lower-mid', 'lower-east'],
      tags: ['dock', 'safe', 'start'],
    },
    {
      id: 'lower-west',
      label: 'Lower West Path',
      position: [-8, 2, 12],
      neighbors: ['smugglers-dock', 'lower-mid', 'ash-ridge', 'bridge-span'],
      tags: ['path'],
    },
    {
      id: 'lower-mid',
      label: 'Ash Approach',
      position: [0, 3, 11],
      neighbors: ['smugglers-dock', 'lower-west', 'lower-east', 'char-pass'],
      tags: ['path', 'danger'],
    },
    {
      id: 'lower-east',
      label: 'Lower East Path',
      position: [8, 2, 12],
      neighbors: ['smugglers-dock', 'lower-mid', 'east-ridge', 'cave-mouth'],
      tags: ['path'],
    },
    {
      id: 'ash-ridge',
      label: 'Ash Ridge',
      position: [-6.5, 6.5, 5.5],
      neighbors: ['lower-west', 'char-pass', 'west-ledge'],
      tags: ['path', 'danger'],
    },
    {
      id: 'char-pass',
      label: 'Char Pass',
      position: [0, 8, 4],
      neighbors: ['lower-mid', 'ash-ridge', 'east-ridge', 'central-spur'],
      tags: ['path', 'danger'],
    },
    {
      id: 'east-ridge',
      label: 'East Ridge',
      position: [6.5, 6.5, 5.5],
      neighbors: ['lower-east', 'char-pass', 'summit-east'],
      tags: ['path'],
    },
    {
      id: 'bridge-span',
      label: 'Bridge Span',
      position: [-11, 5.5, 6],
      neighbors: ['lower-west', 'west-ledge'],
      tags: ['path', 'shortcut'],
    },
    {
      id: 'west-ledge',
      label: 'West Ledge',
      position: [-7.5, 10.5, -1],
      neighbors: ['ash-ridge', 'bridge-span', 'central-spur', 'summit-west'],
      tags: ['path', 'safe'],
    },
    {
      id: 'cave-mouth',
      label: 'Cave Mouth',
      position: [10, 5, 5],
      neighbors: ['lower-east', 'cave-exit'],
      tags: ['path', 'shortcut'],
    },
    {
      id: 'cave-exit',
      label: 'Cave Exit',
      position: [8.5, 10, -1.5],
      neighbors: ['cave-mouth', 'summit-east'],
      tags: ['path', 'shortcut'],
    },
    {
      id: 'central-spur',
      label: 'Central Spur',
      position: [0, 11.5, -1],
      neighbors: ['char-pass', 'west-ledge', 'summit-west', 'summit-east', 'caldera-rim'],
      tags: ['path', 'danger'],
    },
    {
      id: 'summit-west',
      label: 'Summit West',
      position: [-4.5, 14.5, -8],
      neighbors: ['west-ledge', 'central-spur', 'caldera-rim'],
      tags: ['path', 'summit'],
    },
    {
      id: 'summit-east',
      label: 'Summit East',
      position: [4.5, 14.5, -8],
      neighbors: ['east-ridge', 'cave-exit', 'central-spur', 'caldera-rim'],
      tags: ['path', 'summit'],
    },
    {
      id: 'caldera-rim',
      label: 'Caldera Rim',
      position: [0, 17, -12.5],
      neighbors: ['central-spur', 'summit-west', 'summit-east', 'heartstone-dais'],
      tags: ['path', 'summit', 'danger'],
    },
    {
      id: 'heartstone-dais',
      label: 'Heartstone Dais',
      position: [0, 19.25, -16],
      neighbors: ['caldera-rim'],
      tags: ['summit', 'objective'],
    },
  ],
  hazardLanes: [
    {
      id: 'west-fall',
      label: 'West Fall',
      nodeIds: ['heartstone-dais', 'caldera-rim', 'summit-west', 'west-ledge', 'ash-ridge', 'lower-west', 'smugglers-dock'],
    },
    {
      id: 'central-gorge',
      label: 'Central Gorge',
      nodeIds: ['heartstone-dais', 'caldera-rim', 'central-spur', 'char-pass', 'lower-mid', 'smugglers-dock'],
    },
    {
      id: 'east-slide',
      label: 'East Slide',
      nodeIds: ['heartstone-dais', 'caldera-rim', 'summit-east', 'east-ridge', 'lower-east', 'smugglers-dock'],
    },
  ],
};
