import type { CardDefinition } from '@/game/cardTypes';

export const starterCardPool: readonly CardDefinition[] = [
  {
    id: 'dash',
    name: 'Dash',
    moveValue: 4,
    shortLabel: 'Pure speed',
    rulesText: 'Move 4.',
    effect: { kind: 'none' },
  },
  {
    id: 'trek',
    name: 'Trek',
    moveValue: 3,
    shortLabel: 'Cycle hand',
    rulesText: 'Move 3. Draw 1, then discard 1.',
    effect: { kind: 'draw-then-discard', drawCount: 1, discardCount: 1 },
  },
  {
    id: 'clamber',
    name: 'Clamber',
    moveValue: 3,
    shortLabel: 'Terrain hook',
    rulesText: 'Move 3. Ignore one steep-route restriction this turn.',
    effect: { kind: 'future-hook', label: 'Ignore one steep-route restriction.' },
  },
  {
    id: 'shortcut',
    name: 'Shortcut',
    moveValue: 3,
    shortLabel: 'Route hook',
    rulesText: 'Move 3. Use one cave or bridge shortcut edge this turn.',
    effect: { kind: 'future-hook', label: 'Use one cave or bridge shortcut edge.' },
  },
  {
    id: 'brace',
    name: 'Brace',
    moveValue: 2,
    shortLabel: 'Gain Guard',
    rulesText: 'Move 2. Gain Guard until your next turn.',
    effect: { kind: 'grant-status', status: 'guard' },
  },
  {
    id: 'shove',
    name: 'Shove',
    moveValue: 2,
    shortLabel: 'Push rival',
    rulesText: 'Move 2. If adjacent to a rival after moving, push them 1 node.',
    effect: { kind: 'shove-adjacent-rival', distance: 1 },
  },
  {
    id: 'snatch',
    name: 'Snatch',
    moveValue: 2,
    shortLabel: 'Steal objective',
    rulesText: 'Move 2. If adjacent to the Heartstone carrier after moving, steal it.',
    effect: { kind: 'snatch-heartstone' },
  },
  {
    id: 'scramble',
    name: 'Scramble',
    moveValue: 3,
    shortLabel: 'Ignore crowding',
    rulesText: 'Move 3. You may move through one occupied node this turn.',
    effect: { kind: 'allow-occupied-pass' },
  },
  {
    id: 'stoke',
    name: 'Stoke',
    moveValue: 2,
    shortLabel: 'Volcano +2',
    rulesText: 'Move 2. Increase the Volcano Meter by 2.',
    effect: { kind: 'add-volcano-meter', amount: 2 },
  },
  {
    id: 'risky-sprint',
    name: 'Risky Sprint',
    moveValue: 4,
    shortLabel: 'Fast and loud',
    rulesText: 'Move 4. Increase the Volcano Meter by 1.',
    effect: { kind: 'add-volcano-meter', amount: 1 },
  },
  {
    id: 'duck',
    name: 'Duck',
    moveValue: 2,
    shortLabel: 'Hazard hook',
    rulesText: 'Move 2. Ignore the first knockback from an Ember Boulder this round.',
    effect: { kind: 'grant-status', status: 'duck' },
  },
  {
    id: 'seize-ground',
    name: 'Seize Ground',
    moveValue: 2,
    shortLabel: 'Hold your line',
    rulesText: 'Move 2. If you end on a danger space, it does not increase the Volcano Meter.',
    effect: { kind: 'suppress-danger-space-gain' },
  },
] as const;
